dist: trusty
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - openjdk8
  - oraclejdk8
cache:
  directories:
    - $HOME/.mvn/wrapper/
before_script:
- chmod a+x mvnw
script:  
  - java -version
  - ./mvnw clean
  - ./mvnw test
  - ./mvnw install
branches:
  only:
    - master
    - develop