dist: trusty
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - openjdk8
  - oraclejdk8
cache:
  directories:
    - $HOME/.mvn/wrapper/
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)    
before_script:
- chmod a+x mvnw
script:  
  - java -version
  - ./mvnw clean  
  - ./mvnw install
  - ./mvnw test -Pcoverage
after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/jacoco-reports/jacoco.xml
branches:
  only:
    - master
    - develop